### ISSUE TITLE
Progress Bar Doesn't Correctly Compute Subtasks

### ISSUE THREAD

**Issue by mt-xing** [cornell-dti/samwise#171] opened 2019-03-12 18:05 UTC
This seems similar to #144, but is still broken on samwise.today right now.

In this image, I've only completed 1/2 pinned tasks, but I'm getting 2/2 on the progress bar.

![Image](https://user-images.githubusercontent.com/6147405/54224423-da209c00-44cf-11e9-8b14-753b639d28bb.png)

**Comment by SamChou19815** [comment] 2019-03-12 20:01
Strangely, I tried to have a similar setup but I cannot reproduce the problem
<img width="1552" alt="Screen Shot 2019-03-12 at 4 01 02 PM" src="https://user-images.githubusercontent.com/4290500/54232028-21af2400-44e0-11e9-9571-9369b50500cc.png">

**Comment by SamChou19815** [comment] 2019-03-13 23:52
@mt-xing could you find a smallest example that can reproduce this bad behavior? Preferably in dev environment

**Comment by SamChou19815** [comment] 2019-03-14 03:22
The bug should be fixed by #173

**Closed** 2019-03-14 03:23 UTC
Labels: bug, frontend
